# Generated by Django 5.1 on 2024-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CC', 'Credit Card'), ('PP', 'PayPal'), ('BT', 'Bank Transfer')], default='P', max_length=3, null=True),
        ),
    ]
