# Generated by Django 5.1 on 2024-09-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CC', 'Credit Card'), ('PP', 'PayPal'), ('BT', 'Bank Transfer')], default='COD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('S', 'Shipped'), ('F', 'Failed'), ('R', 'Refunded'), ('O', 'Out for Delivery')], default='P', max_length=15, null=True),
        ),
    ]
