# Generated by Django 5.1 on 2024-09-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('S', 'Shipped'), ('F', 'Failed'), ('R', 'Refunded'), ('O', 'Out for Delivery')], default='P', max_length=1, null=True),
        ),
    ]
