# Generated by Django 5.1 on 2024-09-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_cart_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
